package com.coracle.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TgTransOtherpro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.id
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.created_by
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.created_date
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.last_updated_by
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private Long lastUpdatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.last_updated_date
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private Date lastUpdatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.code
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.name
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.supplier
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.pro_type
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private String proType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.unit
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.show_price
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private BigDecimal showPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.package_quantity
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private Long packageQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.take_effect
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private String takeEffect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.remark
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.remove_flag
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private Integer removeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_trans_otherpro.channel_id
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    private Long channelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.id
     *
     * @return the value of tg_trans_otherpro.id
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.id
     *
     * @param id the value for tg_trans_otherpro.id
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.created_by
     *
     * @return the value of tg_trans_otherpro.created_by
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.created_by
     *
     * @param createdBy the value for tg_trans_otherpro.created_by
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.created_date
     *
     * @return the value of tg_trans_otherpro.created_date
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.created_date
     *
     * @param createdDate the value for tg_trans_otherpro.created_date
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.last_updated_by
     *
     * @return the value of tg_trans_otherpro.last_updated_by
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.last_updated_by
     *
     * @param lastUpdatedBy the value for tg_trans_otherpro.last_updated_by
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.last_updated_date
     *
     * @return the value of tg_trans_otherpro.last_updated_date
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.last_updated_date
     *
     * @param lastUpdatedDate the value for tg_trans_otherpro.last_updated_date
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.code
     *
     * @return the value of tg_trans_otherpro.code
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.code
     *
     * @param code the value for tg_trans_otherpro.code
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.name
     *
     * @return the value of tg_trans_otherpro.name
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.name
     *
     * @param name the value for tg_trans_otherpro.name
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.supplier
     *
     * @return the value of tg_trans_otherpro.supplier
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.supplier
     *
     * @param supplier the value for tg_trans_otherpro.supplier
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.pro_type
     *
     * @return the value of tg_trans_otherpro.pro_type
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public String getProType() {
        return proType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.pro_type
     *
     * @param proType the value for tg_trans_otherpro.pro_type
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setProType(String proType) {
        this.proType = proType == null ? null : proType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.unit
     *
     * @return the value of tg_trans_otherpro.unit
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.unit
     *
     * @param unit the value for tg_trans_otherpro.unit
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.show_price
     *
     * @return the value of tg_trans_otherpro.show_price
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public BigDecimal getShowPrice() {
        return showPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.show_price
     *
     * @param showPrice the value for tg_trans_otherpro.show_price
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setShowPrice(BigDecimal showPrice) {
        this.showPrice = showPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.package_quantity
     *
     * @return the value of tg_trans_otherpro.package_quantity
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public Long getPackageQuantity() {
        return packageQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.package_quantity
     *
     * @param packageQuantity the value for tg_trans_otherpro.package_quantity
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setPackageQuantity(Long packageQuantity) {
        this.packageQuantity = packageQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.take_effect
     *
     * @return the value of tg_trans_otherpro.take_effect
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public String getTakeEffect() {
        return takeEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.take_effect
     *
     * @param takeEffect the value for tg_trans_otherpro.take_effect
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setTakeEffect(String takeEffect) {
        this.takeEffect = takeEffect == null ? null : takeEffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.remark
     *
     * @return the value of tg_trans_otherpro.remark
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.remark
     *
     * @param remark the value for tg_trans_otherpro.remark
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.remove_flag
     *
     * @return the value of tg_trans_otherpro.remove_flag
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public Integer getRemoveFlag() {
        return removeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.remove_flag
     *
     * @param removeFlag the value for tg_trans_otherpro.remove_flag
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setRemoveFlag(Integer removeFlag) {
        this.removeFlag = removeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_trans_otherpro.channel_id
     *
     * @return the value of tg_trans_otherpro.channel_id
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_trans_otherpro.channel_id
     *
     * @param channelId the value for tg_trans_otherpro.channel_id
     *
     * @mbg.generated Thu Dec 13 15:22:52 CST 2018
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }
}